### ISSUE TITLE
UE editor crashes when leaving Game mode

### ISSUE THREAD

**Issue by arthursw** [ncsoft/Unreal.js#101]
In an empty project, I created a Blueprint extending Actor that I called `ActorBlueprint`.

I have the following Unreal.js extension (`extension-test.js` in MyProject/Content/Scripts/):

```
const ActorBlueprintGeneratedClass = Blueprint.Load('/Game/ActorBlueprint').GeneratedClass

class ActorBlueprint extends ActorBlueprintGeneratedClass {

    ctor() {
        console.log("ActorBlueprint")
    }
}

function initialize() {
    console.log("New actor blueprint...")

    let Compile = function(x) {
        return require('uclass')()(global, x);
    }

    const ActorBlueprintClass = Compile(ActorBlueprint)
    global.ABP = new ActorBlueprintClass(Engine.GetEditorWorld(), {X:0})
}

function main() {
    setTimeout(initialize, 1000)
}


module.exports = function () {
    main()
    return _ => {
        console.log("Destroying actor blueprint...")
        global.ABP.DestroyActor();
    }
}

```

The editor crashes when I stop the game (when I click `Play`, then hit escape).

Here is the error that I get:

```
<unknown>:-1: Uncaught exception
[2016.08.26-14.22.05:577][338]LogReferenceChain: Searching referencers for Untitled_1. This may take several minutes.
[2016.08.26-14.22.05:738][338]LogReferenceChain: Generating reference graph ...
[2016.08.26-14.22.05:741][338]LogReferenceChain: Level 0 has 1 nodes ...
[2016.08.26-14.22.05:746][338]LogReferenceChain: Level 1 added 1 nodes ...
[2016.08.26-14.22.05:751][338]LogReferenceChain: Level 2 added 0 nodes ...
[2016.08.26-14.22.05:751][338]LogReferenceChain: Generating reference chains ...
Fatal error: [File:D:\Build\++UE4+Release-4.12+Compile\Sync\Engine\Source\Developer\MessageLog\Private\Model\MessageLogListingModel.cpp] [Line: 82] 
Critical Error ActorBlueprint_C0 /Temp/UEDPIE_0_Untitled_1.Untitled_1:PersistentLevel.ActorBlueprint_C0_0 Object from PIE level still referenced. Shortest path from root:    (Object is not currently rooted)

UE4Editor.exe a déclenché un point d'arrêt.
```

I probably miss something when I instantiate the blueprint, but I don't know what...

**Comment by nakosung** [comment]
The issue is about not GC'ed object (uclass) as described. You can clean up artifacts which were introduced during game play session by nulling referenences in your JS and calling `gc()` explicitly.

**Comment by arthursw** [comment]
Ok, but I don't create anything during the game session, I just press start, escape, and it crashes... 

I'll check the console log to see if I missed something.

**Comment by arthursw** [comment]
Also: the problem does not occur every time. Sometimes the game session stops properly without any problem.

**Comment by nakosung** [comment]
Okay, I'll review your code comparing to my case. :)

**Comment by nakosung** [comment]
I confirmed crash related GC leak you reported.

**Comment by arthursw** [comment]
Ok, after a long investigation, I found something:

In an empty C++ project, I didn't have problems with the above code. 

However, the bug happens when I add a custom function, which itself calls a custom function, on the `OnDestroyed` delegate of my ActorBlueprint:

```

class ActorBlueprint extends ActorBlueprintGeneratedClass {

    ctor() {
        console.log("ActorBlueprint ctor")

        this.OnDestroyed.Add(() => {
            console.log("OnDestroyed");
            // !!! Commenting the next line avoids the crash !!!
            this.Delete();
        });
    }

    Delete() {
        console.log("Delete");
    }
}
```

**Comment by arthursw** [comment]
Ok, writing the following code does not crashes, but `this` is not valid anymore in `OnDestroyedCallback`:

```
class ActorBlueprint extends ActorBlueprintGeneratedClass {

    ctor() {
        console.log("ActorBlueprint ctor")
        this.OnDestroyed.Add(this.OnDestroyedCallback);
    }

    OnDestroyedCallback() {
        console.log("OnDestroyed");
        this.Delete();  // does not work since "this" is not valid anymore
    }

    Delete() {
        console.log("Delete");
    }
}
```

**Comment by nakosung** [comment]
I modified your code to be deterministic and found no crashes. Could you try this code?

```js
const ActorBlueprintGeneratedClass = Blueprint.Load('/Game/FirstPerson/NewBlueprint.NewBlueprint').GeneratedClass

class ActorBlueprint extends ActorBlueprintGeneratedClass {

    ctor() {
        console.log("ActorBlueprint ctor")
        this.OnDestroyed.Add(this.OnDestroyedCallback);
    }

    OnDestroyedCallback() {
        console.log("OnDestroyed");
        this.Delete();  // does not work since "this" is not valid anymore !!!
    }

    Delete() {
        console.log("Delete");
    }
}

function initialize() {
    console.log("New actor blueprint...")  

    let Compile = function(x) {  
        return require('uclass')()(global, x);
    }

    const ActorBlueprintClass = Compile(ActorBlueprint)
    global.ABP = new ActorBlueprintClass(Engine.GetEditorWorld(), { X: 0 })
    return function () {
        console.log("Destroying actor blueprint...")
        global.ABP.DestroyActor();
    }
}

module.exports = function () {
    let bye
    let alive = true
    process.nextTick(function () {
        if (!alive) return
        bye = initialize()
    })
    return _ => {
        alive = false 
        if (bye) {            
            bye()
        }
    }
}
```

**Comment by arthursw** [comment]
Ok I confirm that this does not work on my mac (under OS X), with the latest version of Unreal.js (I just cloned & built it), on an empty project (with just a `NewBlueprint` which inherits from `Actor` at `/Game/NewBlueprint.NewBlueprint`).

Same thing: when I use `this.OnDestroyed.Add(() => { this.OnDestroyedCallback() }); `, the UE editor crashes when leaving the game session ; and when I use `this.OnDestroyed.Add(this.OnDestroyedCallback);`, it does not crash, but `this` is not valid in `OnDestroyedCallback`.

**Comment by nakosung** [comment]
Have you tried with new 4.13? There was some change in gc behavior.

**Comment by arthursw** [comment]
Yes, I just tried, I have the same crash with 4.13. But I maybe I can remove `OnDestroyed` on a `BeginPlay`event, and add it back on `EndPlay`? (I didn't try yet)

In a bigger project, I also have problem when I start the game (and it seems to randomly happen sometimes):
```
[2016.09.07-09.59.07:825][443]LogPlayLevel: PIE: Created PIE world by copying editor world from /Temp/Untitled_1.Untitled_1 to /Temp/UEDPIE_0_Untitled_1.Untitled_1 (0.005754s)
Assertion failed: CurrentObject->GetClass()->HasAnyClassFlags(CLASS_TokenStreamAssembled) [File:Runtime/CoreUObject/Private/UObject/FastReferenceCollector.h] [Line: 221] 
```

**Comment by nakosung** [comment]
The issue related to GC was just fixed!

2016년 9월 7일 (수) 오후 7:15, arthursw <notifications@github.com>님이 작성:

**Comment by arthursw** [comment]
great!!!

**Comment by arthursw** [comment]
UE still crashes when I change level (when my ProBuilder extension is activated):

```
2016-11-22 16:01:41.507 UE4Editor[8460:54392] Created a hitchy pipeline state for hash 14000000064 vertex desc: ad1795e0eb37fcf4 (this = 0x1775c82c0)
[2016.11.22-15.01.42:910][301]Cmd: MAP LOAD FILE="../../../Engine/Content/Maps/Templates/VR-Basic.umap" TEMPLATE=1 SHOWPROGRESS=1 FEATURELEVEL=3
[2016.11.22-15.01.42:981][301]LightingResults: New page: Lighting Build
[2016.11.22-15.01.42:982][301]LoadErrors: New page: Loading map: VR-Basic.umap
[2016.11.22-15.01.42:989][301]MapCheck: New page: Map Check
[2016.11.22-15.01.42:989][301]LightingResults: New page: Lighting Build
[2016.11.22-15.01.43:243][301]LogReferenceChain: Searching referencers for Untitled_1. This may take several minutes.
[2016.11.22-15.01.43:436][301]LogReferenceChain: Generating reference graph ...
[2016.11.22-15.01.43:440][301]LogReferenceChain: Level 0 has 8 nodes ...
[2016.11.22-15.01.43:444][301]LogReferenceChain: Level 1 added 22 nodes ...
[2016.11.22-15.01.43:449][301]LogReferenceChain: Level 2 added 36 nodes ...
[2016.11.22-15.01.43:453][301]LogReferenceChain: Level 3 added 35 nodes ...
[2016.11.22-15.01.43:458][301]LogReferenceChain: Level 4 added 2 nodes ...
[2016.11.22-15.01.43:462][301]LogReferenceChain: Level 5 added 0 nodes ...
[2016.11.22-15.01.43:462][301]LogReferenceChain: Generating reference chains ...
[2016.11.22-15.01.43:463][301]LogReferenceChain:   
[2016.11.22-15.01.43:463][301]LogReferenceChain: External Referencers:
[2016.11.22-15.01.43:463][301]LogReferenceChain:   
[2016.11.22-15.01.43:463][301]LogReferenceChain: (root) JavascriptContext /Engine/Transient.JavascriptIsolate_0:JavascriptContext_0->UJavascriptContext::AddReferencedObjects(UObject*, FReferenceCollector&) Address = 0x6fab2950 (filename not found) [in UE4Editor-V8.dylib]
[2016.11.22-15.01.43:463][301]LogReferenceChain:   (target) World /Temp/Untitled_1.Untitled_1
[2016.11.22-15.01.43:463][301]LogReferenceChain:   
[2016.11.22-15.01.43:463][301]LogReferenceChain: (root) JavascriptContext /Engine/Transient.JavascriptIsolate_0:JavascriptContext_0->UJavascriptContext::AddReferencedObjects(UObject*, FReferenceCollector&) Address = 0x6fab2950 (filename not found) [in UE4Editor-V8.dylib]
[2016.11.22-15.01.43:464][301]LogReferenceChain:   (PendingKill) AProBuilder_C0 /Temp/Untitled_1.Untitled_1:PersistentLevel.AProBuilder_C0_0->Outer
[2016.11.22-15.01.43:464][301]LogReferenceChain:     Level /Temp/Untitled_1.Untitled_1:PersistentLevel->OwningWorld
[2016.11.22-15.01.43:464][301]LogReferenceChain:       (target) World /Temp/Untitled_1.Untitled_1
Fatal error: [File:/Users/build/Build/++UE4+Release-4.13+Compile/Sync/Engine/Source/Editor/UnrealEd/Private/EditorServer.cpp] [Line: 1836] 
/Temp/Untitled_1.Untitled_1 still around trying to load ../../../Engine/Content/Maps/Templates/VR-Basic.umap
   (Object is not currently rooted)
```

It seems the ProBuilder Actor is in PendingKill state, but is not fully deleted. What should I do?

**Comment by arthursw** [comment]
I will open another issue to make it more clear.
