### ISSUE TITLE
Manual install fails, install-v8-libs.sh can't download?

### ISSUE THREAD

**Issue by Youdaman** [ncsoft/Unreal.js#172]
```
$ ./install-v8-libs.sh
Download prebuilt V8 libraries for Unreal.js
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100     9    0     9    0     0      8      0 --:--:--  0:00:01 --:--:--     8
Archive:  v8-5.9.211-libs.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of v8-5.9.211-libs.zip or
        v8-5.9.211-libs.zip.zip, and cannot find v8-5.9.211-libs.zip.ZIP, period.
```

Went to https://github.com/ncsoft/Unreal.js-core/releases and downloaded v8-5.9.211-libs.zip manually.

**Comment by crocuis** [comment]
Fixed.

**Comment by crocuis** [comment]
Fixed.

**Comment by Youdaman** [comment]
It still doesn't work because the zip extracts to a folder named `v8-5.9.211-libs` -- it should be just `lib` (I renamed the folder to this and the build works in VS).

**Comment by crocuis** [comment]
Fixed. Thanks! :)

**Comment by Youdaman** [comment]
Can confirm, it's fixed :)

**Comment by mflux** [comment]
I'm still having a similar issue.

    Archive:  v8-..-libs.zip
      End-of-central-directory signature not found.  Either this file is not
      a zipfile, or it constitutes one disk of a multi-part archive.  In the
      latter case the central directory and zipfile comment will be found on
      the last disk(s) of this archive.
    unzip:  cannot find zipfile directory in v8-..-libs.zip,
            and cannot find v8-..-libs.zip.zip, period.
    mv: cannot stat `v8-..-libs': No such file or directory

Windows 10 on Git Bash

**Comment by mflux** [comment]
I had to remove the -e from awk

    #!/bin/sh

    VersionHeader=ThirdParty/v8/include/v8-version.h
    Major=$(cat $VersionHeader | grep MAJOR | awk '{ print $3 }')
    Minor=$(cat $VersionHeader | grep MINOR | awk '{ print $3 }')
    Build=$(cat $VersionHeader | grep BUILD_NUMBER | awk '{ print $3 }')
    Version=$Major.$Minor.$Build
    Tag=V8-$Version
    ZipFile=v8-$Version-libs.zip

    if [ -d "ThirdParty/v8/lib" ]; then
        echo "Unreal.js is ready to build"
    else
        if [ -f "ThirdParty/v8/$ZipFile" ]; then
            echo "Okay you have zip"
        else
            echo "Download prebuilt V8 libraries for Unreal.js"
            (cd ThirdParty/v8; curl -O -L https://github.com/ncsoft/Unreal.js-core/releases/download/$Tag/$ZipFile)
        fi

        (cd ThirdParty/v8; unzip $ZipFile; mv v8-$Version-libs/ lib/)
    fi



    (cd ThirdParty/v8; unzip $ZipFile; mv v8-$Version-libs/ lib/)
fi
