### ISSUE TITLE
Please support 4.26

### ISSUE THREAD

**Issue by nullmu0** [ncsoft/Unreal.js#291]
Would be very grateful

**Comment by edoriontlg** [comment]
I believe that if you build the plugin using 4.26 it should work.

I'm doing this right now, I let you know if this doesnt

**Comment by nullmu0** [comment]
I used in 4.26 and got the error

```
The following modules are missing or built with a different engine version:
V8
  JavascriptUMG
  JavascriptHttp
  JavascriptGraphEditor
  JavascriptEditor
  JavascriptConsole

Would you like to rebuild them now?
```
If I rebuild I will get the following error
```
Error
myproject could not be compiled. Try rebuilding from source manually.
```
My project can no longer be opened, I am sad.
My system is mac OS

**Comment by edoriontlg** [comment]
Idk, I'm on windows, compiled the plugin as explained in the wiki and it worked fine. Didn't used anything in game but I had no crash.

Sorry if I made your project fail. But I hope you'll recover it

**Comment by nullmu0** [comment]
Deleting the Plugins folder project worked

I think I need to change my operating system

**Comment by crocuis** [comment]
Make sure you have updated to the latest version.

**Comment by antoine-pous** [comment]
I personally can't use it with v4.26.0 fresh built from source, here's my log:

```log
Performing 8 actions (16 in parallel)
[1/8] Compile Module.V8.cpp
In file included from /media/gecko/samsung-860/git/discovery-game/client-ue4/Discovery 4.26/Plugins/UnrealJS/Intermediate/Build/Linux/B4D820EA/UE4Editor/Development/V8/Module.V8.cpp:8:
/media/gecko/samsung-860/git/discovery-game/client-ue4/Discovery 4.26/Plugins/UnrealJS/Source/V8/Private/JavascriptContext_Private.cpp:1163:6: error: ignoring return value of function declared with 'warn_unused_result' attribute [-Werror,-Wunused-result]
                                        ProxyFuncMap->Set(context, I.Keyword("ctor"), Function0);
                                        ^~~~~~~~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/media/gecko/samsung-860/git/discovery-game/client-ue4/Discovery 4.26/Plugins/UnrealJS/Source/V8/Private/JavascriptContext_Private.cpp:1164:6: error: ignoring return value of function declared with 'warn_unused_result' attribute [-Werror,-Wunused-result]
                                        ProxyFuncMap->Set(context, I.Keyword("prector"), Function1);
                                        ^~~~~~~~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/media/gecko/samsung-860/git/discovery-game/client-ue4/Discovery 4.26/Plugins/UnrealJS/Source/V8/Private/JavascriptContext_Private.cpp:1170:4: error: ignoring return value of function declared with 'warn_unused_result' attribute [-Werror,-Wunused-result]
                        aftr_v8_template->ToObject(context).ToLocalChecked()->Set(context, I.Keyword("proxy"), ProxyFunctions);
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/media/gecko/samsung-860/git/discovery-game/client-ue4/Discovery 4.26/Plugins/UnrealJS/Source/V8/Private/JavascriptContext_Private.cpp:1315:4: error: ignoring return value of function declared with 'warn_unused_result' attribute [-Werror,-Wunused-result]
                        aftr_v8_template->ToObject(context).ToLocalChecked()->Set(context, I.Keyword("proxy"), ProxyFunctions);
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /media/gecko/samsung-860/git/discovery-game/client-ue4/Discovery 4.26/Plugins/UnrealJS/Intermediate/Build/Linux/B4D820EA/UE4Editor/Development/V8/Module.V8.cpp:12:
/media/gecko/samsung-860/git/discovery-game/client-ue4/Discovery 4.26/Plugins/UnrealJS/Source/V8/Private/JavascriptIsolate_Private.cpp:1216:6: error: ignoring return value of function declared with 'warn_unused_result' attribute [-Werror,-Wunused-result]
                                        function->Call(isolate->GetCurrentContext(), info.This(), 0, nullptr);
                                        ^~~~~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/media/gecko/samsung-860/git/discovery-game/client-ue4/Discovery 4.26/Plugins/UnrealJS/Source/V8/Private/JavascriptIsolate_Private.cpp:1233:6: error: ignoring return value of function declared with 'warn_unused_result' attribute [-Werror,-Wunused-result]
                                        function->Call(isolate->GetCurrentContext(), info.This(), 0, nullptr);
                                        ^~~~~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /media/gecko/samsung-860/git/discovery-game/client-ue4/Discovery 4.26/Plugins/UnrealJS/Intermediate/Build/Linux/B4D820EA/UE4Editor/Development/V8/Module.V8.cpp:13:
/media/gecko/samsung-860/git/discovery-game/client-ue4/Discovery 4.26/Plugins/UnrealJS/Source/V8/Private/JavascriptLibrary.cpp:194:11: warning: 'CreatePackage' is deprecated: Use CreatePackage overload that does not take the first Outer parameter. Specifying non-null outers for UPackages is no longer supported. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile. [-Wdeprecated-declarations]
        return ::CreatePackage(Outer, *PackageName);
                 ^
/media/gecko/samsung-860/git/UnrealEngine/Engine/Source/Runtime/CoreUObject/Public/UObject/UObjectGlobals.h:641:1: note: 'CreatePackage' has been explicitly marked deprecated here
UE_DEPRECATED(4.26, "Use CreatePackage overload that does not take the first Outer parameter. Specifying non-null outers for UPackages is no longer supported.")
^
/media/gecko/samsung-860/git/UnrealEngine/Engine/Source/Runtime/Core/Public/Misc/CoreMiscDefines.h:234:43: note: expanded from macro 'UE_DEPRECATED'
#define UE_DEPRECATED(Version, Message) [[deprecated(Message " Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.")]]
                                          ^
1 warning and 6 errors generated.
LogInit: Warning: Still incompatible or missing module: V8
LogInit: Warning: Still incompatible or missing module: JavascriptUMG
LogInit: Warning: Still incompatible or missing module: JavascriptHttp
LogInit: Warning: Still incompatible or missing module: JavascriptGraphEditor
LogInit: Warning: Still incompatible or missing module: JavascriptEditor
LogInit: Warning: Still incompatible or missing module: JavascriptConsole
LogCore: Engine exit requested (reason: EngineExit() was called)
LogExit: Preparing to exit.
LogModuleManager: Shutting down and abandoning module DesktopPlatform (44)
LogModuleManager: Shutting down and abandoning module PlatformCryptoOpenSSL (42)
LogModuleManager: Shutting down and abandoning module PlatformCryptoTypes (40)
LogModuleManager: Shutting down and abandoning module PlatformCrypto (38)
LogModuleManager: Shutting down and abandoning module AnimationModifiers (36)
LogModuleManager: Shutting down and abandoning module AudioEditor (34)
LogModuleManager: Shutting down and abandoning module PropertyEditor (33)
LogModuleManager: Shutting down and abandoning module TextureCompressor (30)
LogModuleManager: Shutting down and abandoning module RenderCore (28)
LogModuleManager: Shutting down and abandoning module Landscape (26)
LogModuleManager: Shutting down and abandoning module SlateRHIRenderer (24)
LogModuleManager: Shutting down and abandoning module OpenGLDrv (22)
LogModuleManager: Shutting down and abandoning module AnimGraphRuntime (20)
LogModuleManager: Shutting down and abandoning module Renderer (18)
LogModuleManager: Shutting down and abandoning module Engine (16)
LogModuleManager: Shutting down and abandoning module CoreUObject (14)
LogModuleManager: Shutting down and abandoning module NetworkFile (12)
LogModuleManager: Shutting down and abandoning module CookedIterativeFile (10)
LogModuleManager: Shutting down and abandoning module StreamingFile (8)
LogModuleManager: Shutting down and abandoning module SandboxFile (6)
LogModuleManager: Shutting down and abandoning module PakFile (4)
LogModuleManager: Shutting down and abandoning module RSA (3)
LogExit: Exiting.
LogInit: Tearing down SDL.
Exiting abnormally (error code: 1)
```

**Comment by crocuis** [comment]
Fixed. https://github.com/ncsoft/Unreal.js-core/commit/7dc4f660f40a3bc7e74111d627f921032f6547ab

**Comment by mrmowgli** [comment]
I just cloned from master using UE 4.26, and everything compiled.  I still get deprecation warnings though.
```
'SetRealtime' is deprecated: SetRealtime no longer takes in bStoreCurrentValue parameter. For temporary overrides use AddRealtimeOverride Please update your code to the new API before upgrading to the next relea
                EditorViewportClient->SetRealtime(bInRealtime, bStoreCurrentValue);
                                      ^
/home/mrmowgli/UnrealEngine/Engine/Source/Editor/UnrealEd/Public/EditorViewportClient.h:385:2: note: 'SetRealtime' has been explicitly marked deprecated here
        UE_DEPRECATED(4.25, "SetRealtime no longer takes in bStoreCurrentValue parameter. For temporary overrides use AddRealtimeOverride")
        ^
/home/mrmowgli/UnrealEngine/Engine/Source/Runtime/Core/Public/Misc/CoreMiscDefines.h:234:43: note: expanded from macro 'UE_DEPRECATED'
#define UE_DEPRECATED(Version, Message) [[deprecated(Message " Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.")]]
                                          ^
In file included from /home/mrmowgli/unreal-projects/NodejsTest/Plugins/UnrealJS/Intermediate/Build/Linux/B4D820EA/UE4Editor/Development/JavascriptEditor/Module.JavascriptEditor.cpp:20:
/home/mrmowgli/unreal-projects/NodejsTest/Plugins/UnrealJS/Source/JavascriptEditor/JavascriptEditorViewport.cpp:345:25: warning: 'RestoreRealtime' is deprecated: To save and restore realtime state non-permanentl
                EditorViewportClient->RestoreRealtime(bAllowDisable);
                                      ^
/home/mrmowgli/UnrealEngine/Engine/Source/Editor/UnrealEd/Public/EditorViewportClient.h:392:2: note: 'RestoreRealtime' has been explicitly marked deprecated here
        UE_DEPRECATED(4.25, "To save and restore realtime state non-permanently use AddRealtimeOverride and RemoveRealtimeOverride")
        ^
/home/mrmowgli/UnrealEngine/Engine/Source/Runtime/Core/Public/Misc/CoreMiscDefines.h:234:43: note: expanded from macro 'UE_DEPRECATED'
#define UE_DEPRECATED(Version, Message) [[deprecated(Message " Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.")]]
                                          ^
In file included from /home/mrmowgli/unreal-projects/NodejsTest/Plugins/UnrealJS/Intermediate/Build/Linux/B4D820EA/UE4Editor/Development/JavascriptEditor/Module.JavascriptEditor.cpp:26:
/home/mrmowgli/unreal-projects/NodejsTest/Plugins/UnrealJS/Source/JavascriptEditor/JavascriptMenuLibrary.cpp:30:18: warning: 'FToolBarBuilder' is deprecated: FToolBarBuilder constructor that takes in an EOrienta
        FToolBarBuilder Builder(CommandList.Handle, FMultiBoxCustomization::None, nullptr, Orientation);
                        ^
/home/mrmowgli/UnrealEngine/Engine/Source/Runtime/Slate/Public/Framework/MultiBox/MultiBoxBuilder.h:392:2: note: 'FToolBarBuilder' has been explicitly marked deprecated here
        UE_DEPRECATED(4.26, "FToolBarBuilder constructor that takes in an EOrientation is deprecated.  Use one of the specific per-type FToolbarBuilder overrides instead.")
        ^
/home/mrmowgli/UnrealEngine/Engine/Source/Runtime/Core/Public/Misc/CoreMiscDefines.h:234:43: note: expanded from macro 'UE_DEPRECATED'
#define UE_DEPRECATED(Version, Message) [[deprecated(Message " Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.")]]
```

**Comment by adampaigge** [comment]
I just had the exact same problem on Windows as nullmu0, exact same readouts and result. Is this as easy to fix?

**Comment by luojin** [comment]
> I used in 4.26 and got the error
> 
> ```
> The following modules are missing or built with a different engine version:
> V8
>   JavascriptUMG
>   JavascriptHttp
>   JavascriptGraphEditor
>   JavascriptEditor
>   JavascriptConsole
> 
> Would you like to rebuild them now?
> ```
> 
> If I rebuild I will get the following error
> 
> ```
> Error
> myproject could not be compiled. Try rebuilding from source manually.
> ```
> 
> My project can no longer be opened, I am sad.
> My system is mac OS

@nullmu0 i just had the exact same problem on Mac, do you know how to solve it now?
